# -*- mode: ruby -*-
# vi: set ft=ruby :
# the first two lines are modeling for vim or emacs in case you are using them
# read more : https://vim.fandom.com/wiki/Modeline_magic and http://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html


Vagrant.configure("2") do |config|
	config.vm.boot_timeout = 1200
	  config.vm.box = "bento/centos-7"
	  config.vm.box_check_update = false
  
	
	  config.vm.provider "virtualbox" do |v|
		  v.memory = 1024
		  v.cpus = 1
		  v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		  v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	  end
  
	  config.vm.define 'mjalenquS2' do |master|
		  master.vm.hostname = 'mjalenquS2'
		  master.vm.network :private_network, ip: '192.168.42.110'
  
		  master.vm.provider "virtualbox" do |v|
			  v.name = 'mjalenquS2'
		  end
		  master.vm.provision "file", source:"~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
		  master.vm.provision "file", source:"app1.yaml", destination: "/home/vagrant/app1.yml"
		  master.vm.provision "file", source:"app2.yaml", destination: "/home/vagrant/app2.yml"
		  master.vm.provision "file", source:"app3.yaml", destination: "/home/vagrant/app3.yml"
		  master.vm.provision "file", source:"svc.yaml", destination: "/home/vagrant/svc.yml"
		  master.vm.provision "file", source:"ingress.yaml", destination: "/home/vagrant/ingress.yaml"
		  master.vm.provision "shell", path: "p2.sh", privileged: false
	  end
  end