# -*- mode: ruby -*-
# vi: set ft=ruby :
# the first two lines are modeling for vim or emacs in case you are using them
# read more : https://vim.fandom.com/wiki/Modeline_magic and http://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html


Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 1200
	config.vm.box = "bento/centos-stream-8"
	config.vm.box_check_update = false

  
	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.define 'mjalenquS' do |master|
		master.vm.hostname = 'mjalenquS'
		master.vm.network :private_network, ip: '192.168.42.110'

		master.vm.provider "virtualbox" do |v|
			v.name = 'mjalenquS'
		end
		master.vm.provision "file", source:"~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
		master.vm.provision "shell", inline: <<-SHELL
			sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
			sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
			sudo yum update -y
			sudo yum install -y net-tools
			mkdir -p /root/.ssh
			cat /tmp/id_rsa.pub >> /root/.ssh/authorized_keys
			curl -sfL https://get.k3s.io | sh -s - server \
				--write-kubeconfig-mode 644 \
				--node-ip=192.168.42.110 \
				--flannel-iface=eth1
		SHELL
	end

	config.vm.define 'mjalenquSW' do |worker|
		worker.vm.hostname = 'mjalenquSW'
		worker.vm.network :private_network, ip: '192.168.42.111'

		worker.vm.provider "virtualbox" do |v|
			v.name = 'mjalenquSW'
		end
		worker.vm.provision "file", source:"~/.ssh/id_rsa", destination: "/tmp/id_rsa"
		worker.vm.provision "shell", inline: <<-SHELL
			sudo sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
			sudo sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
			sudo yum update -y
			mkdir -p /root/.ssh
			mv /tmp/id_rsa /root/.ssh/id_rsa
			echo "mv done"
			scp -o StrictHostKeyChecking=no root@192.168.42.110:/var/lib/rancher/k3s/server/token /tmp/token
			echo "scp done"
			curl -sfL https://get.k3s.io | sh -s - agent \
    			--server "https://192.168.42.110:6443" \
    			--token-file "/tmp/token" \
				--flannel-iface=eth1
    		kubectl get nodes -o wide
		SHELL
	end
end