# -*- mode: ruby -*-
# vi: set ft=ruby :
# the first two lines are modeling for vim or emacs in case you are using them
# read more : https://vim.fandom.com/wiki/Modeline_magic and http://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html


Vagrant.configure("2") do |config|
	config.vm.boot_timeout = 1200
	  config.vm.box = "bento/centos-7"
	  config.vm.box_check_update = false
  
	
	  config.vm.provider "virtualbox" do |v|
		  v.memory = 4096
		  v.cpus = 5
		  v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		  v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	  end
  
	  config.vm.define 'mjalenquS3' do |master|
		  master.vm.hostname = 'mjalenquS'
		  master.vm.network :private_network, ip: '192.168.42.110'
  
		  master.vm.provider "virtualbox" do |v|
			  v.name = 'mjalenquS3'
		  end
		  master.vm.provision "file", source:"~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
		  master.vm.provision "shell", path: "p3.sh", privileged: false
		  master.vm.provision "shell", path: "deploy.sh", privileged: false
	  end
  end